baseURL = "https://awesome-perlman-888efe.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anake"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[params]
[[menu.main]]
name = "Introduction"
weight = 1
url = "/introduction/"

[[menu.main]]
name = "dummydefinition"
weight = 2
url = "/dummydefinition/"

[[menu.main]]
name = "dummyresource"
weight = 3
url = "/dummyresource/"

[[menu.main]]
name = "dummywalkthrough"
weight = 4
url = "/dummywalkthrough/"
